### PR TITLE
Search Options Feature/1108

### PR DESCRIPTION
**Pull request by kevincrafts**

### CODE REVIEW

**Comment by owenmorrill** [comment]
Merged dev in to test.

**Comment by kreynen** [comment]
Merged the testing changes from #1318. Re-running tests.

**Comment by kreynen** [comment]
Failing on https://travis-ci.org/CuBoulder/express/builds/263494493#L4304

```
When I click the ".mobile-menu-toggle a" element                                          # ExpressContext::iClickTheElement()
    Then I should see "John Doe" in the "Secondary Mobile Menu" region                        # Drupal\DrupalExtension\Context\MinkContext::assertRegionText()
      exception 'Exception' with message 'The text 'John Doe' was not found in the region 'Secondary Mobile Menu' on the page http://127.0.0.1:8080/john-doe#mobile-menu' in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MinkContext.php:435
```

**Comment by kreynen** [comment]
Failing on https://travis-ci.org/CuBoulder/express/builds/263494493#L4305

` When I click the ".mobile-menu-toggle a" element                                          # ExpressContext::iClickTheElement()
    Then I should see "John Doe" in the "Secondary Mobile Menu" region                        # Drupal\DrupalExtension\Context\MinkContext::assertRegionText()
      exception 'Exception' with message 'The text 'John Doe' was not found in the region 'Secondary Mobile Menu' on the page http://127.0.0.1:8080/john-doe#mobile-menu' in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MinkContext.php:435`

**Comment by kevincrafts** [comment]
Did this test ever work?

**Pull request merged**
